# -*- coding: utf-8 -*-
"""ChatBot_BUSHI_encord.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1juY826cainVxPW9J8njN3VOnfnbxi3bx
"""

!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time
# ブラウザをheadlessモード実行
options = webdriver.ChromeOptions()
#ヘッドレスモード（バックグラウンドで起動）で実行。コラボの場合、必須。
options.add_argument('--headless')
#サンドボックスモードの解除。これも必須。
options.add_argument('--no-sandbox')
#これも設定した方がよい。
options.add_argument('--disable-dev-shm-usage')

#インスタンス化
driver = webdriver.Chrome('chromedriver',options=options)
#指定したドライバーが見つかるまで待機
driver.implicitly_wait(10)

#urlの指定
url="http://monjiro.net/"

# driver.get(url)
# time.sleep(3)

import requests
from IPython.display import Image
def talk_api(message):
    apikey = "DZZUN6YqBzB1MqSfwaGO5wG4R3P96jQd"
    talk_url = "https://api.a3rt.recruit.co.jp/talk/v1/smalltalk"
    payload = {"apikey": apikey, "query": message}
    response = requests.post(talk_url, data=payload)
    try:
        return response.json()["results"][0]["reply"]
    except:
        print(response.json())
        return "ごめんなさい。もう一度教えて下さい。"

def main():
     while(True):
         print("あなた：")
         message = input()

         driver.get(url)
         time.sleep(3)
         driver.refresh()

         form = talk_api(message)

         # フォームに初めから入力されている例文を削除
         driver.find_element(By.XPATH,"//*[@id='before']").clear()
         # フォームにチェットの返信内容を入力
         driver.find_element(By.XPATH,"//*[@id='before']").send_keys(form)

         # 変換ボタンをクリック
         btn = driver.find_element(By.XPATH,"//*[@id='button']")
         btn.click()

         time.sleep(5)
         html = driver.page_source
         BeautifulSoup(html,"lxml")

         display(Image('/content/bushi.png'))
         results = driver.find_elements(By.TAG_NAME,"strong")
         # スクレイピングでページ内の関係ない文字列（広告）を引っ張ってきてしまうため、取り除く
         beforeA =  "国内格安航空券を" 
         afterA =  ""
         beforeB =  "価格比較！" 
         afterB =  ""
         print("武士：" )
         for r in results:
           print(r.text.replace(beforeA , afterA).replace(beforeB , afterB), end="")
         print("")

if __name__ == "__main__":
     main()